"""
Veridian Corp Official Knowledge Base & Policies (KB-01 to KB-10 + Asset Management Policy)
Grounded strictly in Assessment 2 PDF specification for the week of September 21–25, 2026.
"""

VERIDIAN_KNOWLEDGE_BASE = [
    {
        "kb_id": "KB-01",
        "title": "Password Reset Policy",
        "category": "Authentication & Access",
        "content": (
            "Employees can reset their own password via the self-service portal at any time. "
            "If locked out after 5 failed attempts, contact IT to unlock the account manually. "
            "No approval required."
        ),
        "summary": "Self-service reset portal available anytime. 5 failed attempts trigger account lockout requiring IT manual unlock. No approval needed.",
        "requires_approval": False,
        "approval_authority": None,
        "lockout_threshold": 5,
    },
    {
        "kb_id": "KB-02",
        "title": "VPN Access Policy",
        "category": "Network & Security",
        "content": (
            "VPN access is granted automatically to all full-time employees. Contractors require manager approval "
            "submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee."
        ),
        "summary": "Full-time employees receive VPN access automatically. Contractors require manager approval via request form. Credentials expire every 90 days (self-renewed).",
        "requires_approval": True,
        "approval_authority": "Manager (for contractors)",
        "expiry_days": 90,
    },
    {
        "kb_id": "KB-03",
        "title": "Laptop Replacement Policy",
        "category": "Hardware & Assets",
        "content": (
            "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. "
            "Requests must be raised at least 2 weeks in advance of intended replacement."
        ),
        "summary": "Eligible after 3 years of service or verified hardware failure. Requires at least 2 weeks advance request notice.",
        "requires_approval": True,
        "approval_authority": "IT & Finance (cross-referenced with Asset Management Policy)",
        "eligibility_years": 3,
        "advance_notice_weeks": 2,
    },
    {
        "kb_id": "KB-04",
        "title": "Software Installation Requests",
        "category": "Software & Applications",
        "content": (
            "Standard software (listed in the approved catalog) can be self-installed. "
            "Non-catalog software requires IT Security review, which takes 3–5 business days."
        ),
        "summary": "Standard catalog software is self-service install. Non-catalog applications (including browser extensions/tools) require IT Security review (3–5 business days).",
        "requires_approval": True,
        "approval_authority": "IT Security",
        "sla_business_days": "3-5",
    },
    {
        "kb_id": "KB-05",
        "title": "Printer Troubleshooting",
        "category": "Hardware & Peripherals",
        "content": (
            "For printer issues, first check the printer queue and restart the print spooler. "
            "If the issue persists after restart, log a ticket with the printer’s asset tag."
        ),
        "summary": "First check printer queue and restart local print spooler service. If unresolved, create an IT ticket providing the printer asset tag.",
        "requires_approval": False,
        "approval_authority": None,
    },
    {
        "kb_id": "KB-06",
        "title": "Email Mailbox Quota",
        "category": "Communication & Email",
        "content": (
            "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. "
            "Quota increases beyond 25GB require manager approval and are capped at 50GB."
        ),
        "summary": "Default mailbox quota is 25GB (archive old emails). Increases above 25GB require manager approval and have a hard cap of 50GB.",
        "requires_approval": True,
        "approval_authority": "Manager",
        "default_quota_gb": 25,
        "max_quota_gb": 50,
    },
    {
        "kb_id": "KB-07",
        "title": "Guest Wi-Fi Access",
        "category": "Network & Visitors",
        "content": (
            "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. "
            "No IT ticket required."
        ),
        "summary": "24-hour guest Wi-Fi passes can be generated directly by any employee at the front-desk kiosk. No IT ticket needed.",
        "requires_approval": False,
        "approval_authority": None,
        "validity_hours": 24,
    },
    {
        "kb_id": "KB-08",
        "title": "Expense Software Access",
        "category": "Enterprise Systems",
        "content": (
            "Access to the expense management tool is granted by Finance, not IT. "
            "IT can only assist with login/technical issues once an account already exists."
        ),
        "summary": "Finance department provisions new user accounts for the expense tool. IT handles technical/login support only after account creation.",
        "requires_approval": True,
        "approval_authority": "Finance (for provisioning)",
    },
    {
        "kb_id": "KB-09",
        "title": "Security Incident Reporting",
        "category": "Information Security",
        "content": (
            "Any suspected phishing email, malware, or unauthorized access attempt must be reported to "
            "security@veridian-corp.example immediately and should not be forwarded to other employees."
        ),
        "summary": "Report phishing, malware, or suspicious access to security@veridian-corp.example immediately. Do NOT forward malicious/phishing emails to colleagues.",
        "requires_approval": False,
        "approval_authority": "IT Security (Incident Response)",
        "security_email": "security@veridian-corp.example",
    },
    {
        "kb_id": "KB-10",
        "title": "Work-From-Home Equipment",
        "category": "Facilities & Equipment",
        "content": (
            "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance "
            "(chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved."
        ),
        "summary": "Remote work > 3 days/week qualifies for one-time allowance (chair, monitor). Requires Manager sign-off and Finance approval. IT executes shipping after approvals.",
        "requires_approval": True,
        "approval_authority": "Manager (Sign-off) & Finance (Processing)",
        "min_remote_days": 3,
    },
    {
        "kb_id": "ASSET-01",
        "title": "Asset Management Policy (Finance & Assets Extract)",
        "category": "Asset Governance",
        "content": (
            "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle "
            "from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval."
        ),
        "summary": "Standard 4-year hardware refresh cycle. Replacement before 4 years requires Finance sign-off in addition to IT approval.",
        "requires_approval": True,
        "approval_authority": "Finance & IT",
        "refresh_cycle_years": 4,
    },
]
